trigger:
- main

pool: azurevm

stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - job: Build
      displayName: Build job
      pool: azurevm
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'myclusterconnection'
          repository: 'azureconrepo'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'

