trigger:
- main

pool: azurevm

stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - job: Build
      displayName: Build job
      pool: azurevm
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'myclusterconnection'
          repository: 'azureconrepo'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifest'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          OverWrite: true
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'kube-manifests'
          publishLocation: 'Container'

